<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10941" started-at="2014-02-25T11:02:21Z" finished-at="2014-02-25T11:02:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10941" started-at="2014-02-25T11:02:21Z" finished-at="2014-02-25T11:02:31Z">
      <class name="com.bs.selenium.functional.ClickToggleButtonTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.bs.selenium.functional.ClickToggleButtonTest@38653ad5]" name="init" is-config="true" duration-ms="5215" started-at="2014-02-25T13:02:21Z" finished-at="2014-02-25T13:02:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="mayBeLogout()[pri:0, instance:com.bs.selenium.functional.ClickToggleButtonTest@38653ad5]" name="mayBeLogout" is-config="true" duration-ms="42" started-at="2014-02-25T13:02:26Z" finished-at="2014-02-25T13:02:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mayBeLogout -->
        <test-method status="FAIL" signature="testToggleButton()[pri:0, instance:com.bs.selenium.functional.ClickToggleButtonTest@38653ad5]" name="testToggleButton" duration-ms="5653" started-at="2014-02-25T13:02:26Z" finished-at="2014-02-25T13:02:31Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.bs.selenium.functional.ClickToggleButtonTest.testToggleButton(ClickToggleButtonTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testToggleButton -->
        <test-method status="PASS" signature="stop()[pri:0, instance:com.bs.selenium.functional.ClickToggleButtonTest@38653ad5]" name="stop" is-config="true" duration-ms="1594" started-at="2014-02-25T13:02:32Z" finished-at="2014-02-25T13:02:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
      </class> <!-- com.bs.selenium.functional.ClickToggleButtonTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
